---
# Tasks file for ansible-role-gnome-config: Install Extension

# @todo Find out where exactly gnome-extensions is available and use it here if
#   possible (i.e. gnome-extensions enable ...).
- name: Install extension with gnome-shell-extension-tool.
  ansible.builtin.command: "gnome-shell-extension-tool enable {{ gnome_extension_uuid }}" # noqa no-changed-when
  become: "{{ gnome_user }}"
