---
name: Molecule Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  molecule:
    runs-on:
      - ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: ${{ github.repository }}
      - uses: gofrolist/molecule-action@v2
